name: blobcache
description: Dart client for the Blobcache API.
version: 0.1.0
homepage: https://blobcache.io
repository: https://github.com/blobcache/blobcache

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  ffi: ^2.1.0
  http: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0